#spring.h2.console.enable=true
#spring.datasource.generate-unique-name=false
#spring.datasource.name=runner
spring.datasource.url=jdbc:postgresql://localhost:5432/runner
spring.datasource.username=parimi
spring.datasource.password=password

spring.sql.init.mode=always